name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: getDeps
      run: sudo apt-get install liballegro5-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build_for_windows:
    runs-on: windows-latest
    steps:
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
    - name: Build Allegro
      run: |
        git clone https://github.com/liballeg/allegro5.git
        cd allegro5
        git checkout v5.2.8
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
