name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: getDeps
      run: sudo apt-get install liballegro5-dev
    - name: Build (Release)
      run: | 
        cargo build --target=x86_64-unknown-linux-gnu --release
        #cargo build --target=x86_64-pc-windows-gnu --release
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v2
      with:
        name: rusty_rogue
        path: |
          target/x86_64-unknown-linux-gnu/release/
          #    - name: Upload Windows Binary
          #      uses: actions/upload-artifact@v2
          #      with:
          #        name: rusty_rogue
          #        path: |
          #          target/x86_64-pc-windows-gnu/release/rusty_rogue
